### ISSUE TITLE
JUnit report generated by Unit test fail to be parsed

### ISSUE THREAD

**Issue by franklychilled** [franklychilled/nightwatch-slack-notification-buildkite-plugin#124]
Creating ui_36_3d01bc96-f054-46ce-998f-23204de3d0df_slack-notification_1 ... done
--
  | Attaching to ui_36_3d01bc96-f054-46ce-998f-23204de3d0df_slack-notification_1
  | slack-notification_1  \| parsing /app/reports/output/TESTS-HeadlessChrome_88.0.4324_(Linux_0.0.0).xml
  | slack-notification_1  \| boom!
  | slack-notification_1  \| TypeError: Cannot read property 'testsuite' of undefined
  | slack-notification_1  \|     at stats (/app/dist/testcaseStats.js:42:42)
  | slack-notification_1  \|     at arrayMap (/app/node_modules/lodash/lodash.js:639:23)
  | slack-notification_1  \|     at Object.map (/app/node_modules/lodash/lodash.js:9580:14)
  | slack-notification_1  \|     at Object.allStats (/app/dist/testcaseStats.js:92:14)
  | slack-notification_1  \|     at /app/dist/testcaseStats.js:105:37
  | slack-notification_1  \|     at Generator.next (<anonymous>)
  | slack-notification_1  \|     at /app/dist/testcaseStats.js:27:71
  | slack-notification_1  \|     at new Promise (<anonymous>)
  | slack-notification_1  \|     at __awaiter (/app/dist/testcaseStats.js:23:12)
  | slack-notification_1  \|     at Object.addStatsToCommit (/app/dist/testcaseStats.js:104:51)
  | slack-notification_1  \| {"testsuite":{"$":{"name":"HeadlessChrome 88.0.4324 (Linux 0.0.0)","package":"","timestamp":"2021-03-

**Comment by franklychilled** [comment]
Fixed in https://github.com/franklychilled/nightwatch-slack-notification-buildkite-plugin/commit/eb97740002813f1cc0ad70ffeb6b1aef3aa4b2c9
